language: generic
addons:
  apt:
    packages:
      - sshpass
before_script:
  - echo -e "Host blockdeals.org\n\tStrictHostKeyChecking no\n\tUser blockdeals\n" >> ~/.ssh/config
script: sshpass -e ssh blockdeals.org blockdeals/deploy.sh
