language: generic
addons:
  apt:
    packages:
      - sshpass
before_script:
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n\tUser blockdeals\n" >> ~/.ssh/config
script: sshpass -e ssh ${DEPLOY_HOST} blockdeals/deploy.sh
